server:
  port: 8080

spring:

  application:
    name: api-gateway

  cloud:
    gateway:

      # 🔥🔥🔥 CORS CONFIG (MANDATORY)
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
          filters:
            - name: CircuitBreaker
              args:
                name: customerCB
                fallbackUri: forward:/fallback/customer

        - id: loan-application-service
          uri: lb://loan-application-service
          predicates:
            - Path=/api/loans/**

        - id: loan-processing-service
          uri: lb://loan-processing-service
          predicates:
            - Path=/api/processing/**

        - id: repayment-service
          uri: lb://repayment-service
          predicates:
            - Path=/api/repayments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.springframework.cloud.gateway: INFO
