server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/auth_db

security:
  jwt:
    secret: THIS_IS_A_VERY_SECURE_SECRET_KEY_FOR_LMS_256_BITS
    expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
