server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/auth_db

jwt:
  secret: EnPbZ5oar9qDWB9QmBDxP6HaLChzDEY7pLI+E7NZ09qpQkCR+vZyioF6z1fWWx/3
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
