server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/auth_db

jwt:
  secret: LMS_SECRET_KEY_123456789
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
