spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer_db

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: p9A2ZK8xLMSAuthSecretKey_2026_SECURE_64CHAR_RANDOM_XYZ

logging:
  level:
    com.lms.customer: DEBUG
