spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer_db

security:
  jwt:
    secret: THIS_IS_A_VERY_SECURE_SECRET_KEY_FOR_LMS_CUSTOMER_SERVICE
    expiration: 86400000   # 24 hours in ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    com.lms.customer: DEBUG
