spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer_db

security:
  jwt:
    secret: EnPbZ5oar9qDWB9QmBDxP6HaLChzDEY7pLI+E7NZ09qpQkCR+vZyioF6z1fWWx/3

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.lms.customer: DEBUG
