spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer_db

security:
  jwt:
    secret: THIS_IS_A_VERY_SECURE_SECRET_KEY_FOR_LMS_AUTH_SERVICE_256_BITS

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.lms.customer: DEBUG
