server:
  port: 0   # Dynamic port for Eureka (REQUIRED)

spring:
  application:
    name: loan-processing-service

  data:
    mongodb:
      uri: mongodb://mongo:27017/loan_processing_db

  kafka:
    bootstrap-servers: kafka:9092   # ❗ MUST NOT be localhost

    consumer:
      group-id: loan-processing-group
      auto-offset-reset: earliest
      enable-auto-commit: true

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.lms.loanprocessing.event
        spring.json.use.type.headers: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
