spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification_db

  mail:
    host: smtp.gmail.com
    port: 587
    username: akankshyap1402@gmail.com
    password: zmbgulixebisrqlb
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

